### ISSUE TITLE
Unable to pull bookmarks in Chrome (and Chrome based Edge)

### ISSUE THREAD

**Issue by abalter** [Cleod9/syncmarx-webext#30]
Hey, I love this extension. I used to use it exclusively because I only used firefox. Now I'm using Edge as well for work. The chrome store version installed and functions. However, it fails to pull the bookmarks.

I was able to snoop around with developer tools a bit and the error is about an incompatible bookmark format.

```
Uncaught (in promise) Error: Incompatible bookmark format
    at L (app.js:23:200144)
    at app.js:23:208621
```

I'm a data programmer, not a software or web programmer, so I'm not sure what more I can do to diagnose the problem. But if we can work on it together, I'll do what I can. 

Is there a way I can run the plugin with non-minimized code to make debugging easier?

**Comment by abalter** [comment]
Hey, I just read further down the readme, and you have some debugging suggestions. I'll see what I can do.

There is also a caveat about

>Will not manage browser-specific bookmark functionality due to Web Extension spec limitations (e.g. Seperators, tags, keywords, description, favicons, etc.)

So, I'll watch out for that. So far, I haven't even found a spec sheet for the different bookmark formats.

**Comment by abalter** [comment]
So, here is the issue:

https://github.com/Cleod9/syncmarx-webext/blob/498cb3235fc57d1f8759238343bd9cb0c060cced/src/core/BookmarkManager.js#L115

So, I'm going to try to run it in the test mode you described. I'll add some additional output to see if I can figure out what is incompatible.

**Comment by Cleod9** [comment]
> So, here is the issue:
> 
> https://github.com/Cleod9/syncmarx-webext/blob/498cb3235fc57d1f8759238343bd9cb0c060cced/src/core/BookmarkManager.js#L115
> 
> So, I'm going to try to run it in the test mode you described. I'll add some additional output to see if I can figure out what is incompatible.

Hi, thanks for the initial investigation! Apologies for the lack of support on this extension, it's just difficult to find the time nowadays...

Anyway, so if it's erroring there that means the base call for [`bookmarks.create`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/create) failed for some reason. I have the code fall back to the `incomingUrlFixer` method and attempt to create the bookmark again with some browser-specific tweaks to work around issues like this. This means there must be something unique about how Edge handles bookmarks that needs to be handled here. The true error message however is probably being swallowed in the promise chain. I haven't tested this in Edge before, though when I get a chance I'll see if I can track what's happening

**Comment by itasterix** [comment]
I have the same problem:
"Failed to pull bookmark data"

I see this issue is opened from a long time and not solved anymore.
